### PR TITLE
Python script to download coqgym data

### PR DESCRIPTION
**Pull request by brando90**
Feel free to try it and give me feedback!

### CODE REVIEW

**Comment by yangky11** [comment]
Thanks! I'll take a look this weekend.

**Comment by yangky11** [comment]
I get this error when running donwload_coqgym_data.py:
```
Traceback (most recent call last):
  File "donwload_coqgym_data.py", line 92, in <module>
    print(f'download path = {path}')
NameError: name 'path' is not defined
```

**Comment by brando90** [comment]
> I get this error when running donwload_coqgym_data.py:
> 
> ```
> Traceback (most recent call last):
>   File "donwload_coqgym_data.py", line 92, in <module>
>     print(f'download path = {path}')
> NameError: name 'path' is not defined
> ```

I think this is the location to download. Try this:

```
path = Path('~/data_lib/coqgym/').expanduser()
```

You might need to create the folder with 

```
path.mkdir(parents=False, exist_ok=False)
```
inside of the functions so the user doesn't worry about missing folders.

**Comment by yangky11** [comment]
thx

**Pull request merged**
